# Generated by Django 5.2.4 on 2025-09-21 22:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calorias_por_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion_dias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group', verbose_name='groups')),
                ('id_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymdb.rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida')], max_length=7)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('id_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.membresia')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Entrenamiento',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('series_realizadas', models.IntegerField(blank=True, null=True)),
                ('repeticiones_realizadas', models.IntegerField(blank=True, null=True)),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.ejercicio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina_Dia_Ejercicio',
            fields=[
                ('id_rutina_dia_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=9)),
                ('nombre_ejercicio', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymdb.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina_Ejercicio',
            fields=[
                ('id_rutina_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.rutina')),
            ],
        ),
    ]
