# Generated by Django 5.2.5 on 2025-08-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calorias_por_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion_dias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('id_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.membresia')),
            ],
        ),
        migrations.AddField(
            model_name='membresia',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.plan'),
        ),
        migrations.CreateModel(
            name='Rutina_Dia_Ejercicio',
            fields=[
                ('id_rutina_dia_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=9)),
                ('nombre_ejercicio', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymdb.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina_Ejercicio',
            fields=[
                ('id_rutina_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('id_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymdb.usuario')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.rol')),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='id_coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.usuario'),
        ),
        migrations.CreateModel(
            name='Registro_Entrenamiento',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('series_realizadas', models.IntegerField(blank=True, null=True)),
                ('repeticiones_realizadas', models.IntegerField(blank=True, null=True)),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gymdb.ejercicio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='membresia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdb.usuario'),
        ),
    ]
